


 export const  URI = 'http://localhost:8000/card/'
export const  URI2 = 'http://localhost:8000/questions/'; 
export const  URI3 = 'http://localhost:8000/options/';
export const  URI4 = 'http://localhost:8000/login';
export const  URI5 = 'http://localhost:8000/usuarios/';
export const  URI6 = 'http://localhost:8000/votes/';
export const  URI7 = 'http://localhost:8000/Link/';
export const URI8 = 'http://localhost:8000/api/votacion/estado/';
export const URI9 = 'http://localhost:8000/api/votacion/estado/';
export const URI10 = 'http://localhost:8000/CreateExcel/';
export const URI11 = 'http://localhost:8000/votes/v/';
export const URI12 = 'http://localhost:8000/UsersDefinitive/c/';
export const URI13 = 'http://localhost:8000/UsersDefinitive/';
export const UIR14 = 'http://localhost:8000/UsersDefinitive/N/';
export const URI15 = 'http://localhost:8000/usuarios/c/';
export const URI16 = 'http://localhost:8000/usuarios/o/';
export const URI17 = 'http://localhost:8000/UsersDefinitive/A/';
export const URI18 = 'http://localhost:8000/UsersDefinitive/';
export const URI19 = 'http://localhost:8000/card/id/';
export const URI20 = 'http://localhost:8000/card/E/';
export const URI21 = 'http://localhost:8000/DataAutenticathed';
export const URI22 = 'http://localhost:8000/usuarios/A/';
export const URI23 = 'http://localhost:8000/usuarios/api/get-column';
export const URI24 = 'http://localhost:8000/Propuestas/api/';
export const URI25 = 'http://localhost:8000/Propuestas/'; 
export const URI26 = 'http://localhost:8000/UsersDefinitive/pdf/';
export const URI27 = 'http://localhost:8000/UsersDefinitive/Excel/';
export const URI28 = 'http://localhost:8000/UsersDefinitive/OPE/getAll/';
export const URI29 = 'http://localhost:8000/UsersDefinitive/Quorum/setquorum/';
export const URI30 = 'http://localhost:8000/Votes/Votes/';
export const URI31 = 'http://localhost:8000/UsersDefinitive/CreateUser/Apoderado/';
export const URI32 = 'http://localhost:8000/UsersDefinitive/ShareUserOne/';
export const URI33 = 'http://localhost:8000/Usuarios/GetuserOne/oneuser/';
export const URI34 = 'http://localhost:8000/usuarios/update/';
export const URI35 = 'http://localhost:8000/UsersDefinitive/update/'; 


/*  export const URI = 'https://serverapivote.co.control360.co/card/';
export const URI2 = 'https://serverapivote.co.control360.co/questions/';
export const URI3 = 'https://serverapivote.co.control360.co/options/';
export const URI4 = 'https://serverapivote.co.control360.co/login';
export const URI5 = 'https://serverapivote.co.control360.co/usuarios/';
export const URI6 = 'https://serverapivote.co.control360.co/votes/';
export const URI7 = 'https://serverapivote.co.control360.co/Link/';
export const URI8 = 'https://serverapivote.co.control360.co/api/votacion/estado/';
export const URI9 = 'https://serverapivote.co.control360.co/api/votacion/estado/';
export const URI10 = 'https://serverapivote.co.control360.co/CreateExcel/';
export const URI11 = 'https://serverapivote.co.control360.co/votes/v/';
export const URI12 = 'https://serverapivote.co.control360.co/UsersDefinitive/c/';
export const URI13 = 'https://serverapivote.co.control360.co/UsersDefinitive/';
export const UIR14 = 'https://serverapivote.co.control360.co/UsersDefinitive/N/';
export const URI15 = 'https://serverapivote.co.control360.co/usuarios/c/';
export const URI16 = 'https://serverapivote.co.control360.co/usuarios/o/';
export const URI17 = 'https://serverapivote.co.control360.co/UsersDefinitive/A/';
export const URI18 = 'https://serverapivote.co.control360.co/UsersDefinitive/';
export const URI19 = 'https://serverapivote.co.control360.co/card/id/';
export const URI20 = 'https://serverapivote.co.control360.co/card/E/';
export const URI21 = 'https://serverapivote.co.control360.co/DataAutenticathed';
export const URI22 = 'https://serverapivote.co.control360.co/usuarios/A/';
export const URI23 = 'https://serverapivote.co.control360.co/usuarios/api/get-column';
export const URI24 = 'https://serverapivote.co.control360.co/Propuestas/api/';
export const URI25 = 'https://serverapivote.co.control360.co/Propuestas/';
export const URI26 = 'https://serverapivote.co.control360.co/UsersDefinitive/pdf/';
export const URI27 = 'https://serverapivote.co.control360.co/UsersDefinitive/Excel/';
export const URI28 = 'https://serverapivote.co.control360.co/UsersDefinitive/OPE/getAll/';
export const URI29 = 'https://serverapivote.co.control360.co/UsersDefinitive/Quorum/setquorum/';
export const URI30 = 'https://serverapivote.co.control360.co/Votes/Votes/'; 
export const URI31 = 'https://serverapivote.co.control360.co/UsersDefinitive/CreateUser/Apoderado/';
export const URI32 = 'https://serverapivote.co.control360.co/UsersDefinitive/ShareUserOne/';
export const URI33 = 'https://serverapivote.co.control360.co/Usuarios/GetuserOne/oneuser/';
export const URI34 = 'https://serverapivote.co.control360.co/usuarios/update/';
export const URI35 = 'https://serverapivote.co.control360.co/UsersDefinitive/update/';
 */